-- =====================================================
-- Таблица: properties (объекты недвижимости)
-- =====================================================
CREATE TABLE IF NOT EXISTS properties (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  "buildingName" TEXT,
  address TEXT NOT NULL,
  price BIGINT NOT NULL,
  area REAL NOT NULL,
  rooms INT DEFAULT 1,
  floor INT DEFAULT 1,
  "totalFloors" INT DEFAULT 1,
  view TEXT,
  features JSONB DEFAULT '[]',
  district TEXT NOT NULL,
  microdistrict TEXT,
  type TEXT DEFAULT 'apartment',
  "dealType" TEXT DEFAULT 'sale',
  "completionDate" TEXT,
  "yearBuilt" INT,
  "kitchenArea" REAL,
  "imageKey" TEXT,
  description TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "createdBy" TEXT
);

ALTER TABLE properties ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated users" ON properties
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- =====================================================
-- Таблица: news (новости)
-- =====================================================
CREATE TABLE IF NOT EXISTS news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag TEXT DEFAULT 'Новости',
  "readTime" TEXT DEFAULT '5 min read',
  title TEXT NOT NULL,
  excerpt TEXT,
  date TEXT,
  author TEXT NOT NULL,
  image TEXT,
  "authorAvatar" TEXT,
  "createdAt" TIMESTAMPTZ DEFAULT NOW(),
  "createdBy" TEXT
);

ALTER TABLE news ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all for authenticated users" ON news
  FOR ALL USING (auth.role() = 'authenticated')
  WITH CHECK (auth.role() = 'authenticated');

-- =====================================================
-- Таблица: applications (заявки) — уже существует
-- Добавляем политику для чтения всех заявок админом
-- =====================================================
CREATE POLICY "Allow read all for authenticated" ON applications
  FOR SELECT USING (auth.role() = 'authenticated');
